# Generated by Django 3.0.2 on 2020-01-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producername', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Produces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie')),
                ('producerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Producer')),
            ],
        ),
    ]
